# Generated by Django 5.1.4 on 2025-02-07 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="following_friendship_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follower_friendship_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["from_user_id", "created_at"],
                        name="friendships_from_us_6c3805_idx",
                    ),
                    models.Index(
                        fields=["to_user_id", "created_at"],
                        name="friendships_to_user_3e9003_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_user", "to_user"), name="unique_friendship"
                    )
                ],
            },
        ),
    ]
