# Generated by Django 5.1.4 on 2025-02-07 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ("user", "-created_at")},
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(
                fields=["user", "created_at"], name="tweets_twee_user_id_ba0f61_idx"
            ),
        ),
    ]
